---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=12mm
      - left=16mm
      - right=16mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertinus
    colorlinks: true
    fontsize: '16'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
---
<!-- TITLE -->
\begin{center}
{\fontsize{35}{50}\selectfont \textbf{Alan J Averett}}
\end{center}

<!-- CONTACT INFO -->
\begin{center} 832.856.4666 | ajaverett0@gmail.com | linkedin.com/in/ajaverett | ajaverett.github.io
\end{center}
\vspace{12pt}

<!-- EDUCATION: 1ST BULLET -->
\begin{large}
  {\bf EDUCATION}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf Brigham Young University- Idaho}\end{flushleft}
    \begin{flushright}Rexburg, ID\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}B.Sc. Data Science, Statistics; \textit{Major GPA: 3.8/4.0} \end{flushleft}
    \begin{flushright} Apr 2020 - Dec 2023\end{flushright}
  \end{multicols}
  \vspace{-0.25cm}
\end{large}
 * **Certifications**: Web and Computer Programming (3.7/4.0); Machine Learning (4.0/4.0)
 * **Leadership**: Chi Delta Society, Society of Hispanic Professional Engineers (SHPE), Data Science and AI Society

\vspace{0.2cm}


\vspace{7pt}

<!-- EXPERIENCE : 1ST BULLET-->
\begin{large}{\bf EXPERIENCE}
\vspace{3pt}
\hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://wpaintel.com/about/}{WPA Intelligence}}\end{flushleft}
    \begin{flushright}Washington D.C.\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Machine Learning Intern}\end{flushleft}
    \begin{flushright}Jul 2022 - Nov 2022\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Created digestible reports for 80+ political campaigns by analyzing/visualizing voter data trends with machine learning models that predicted ideological disposition and turnout using \textbf{\textit{R's tidyverse}}
* Significantly decreased polling production time by automating sampling methodologies using R's statistical libraries
* Increased accuracy and AUC for all future machine learning models by using \textbf{\textit{GIS}} data to categorize over 100 million records of voter data into 12 granularities of population density using \textbf{\textit{R's sf}} and other geospatial libraries

\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://www.familysearch.org/help/oral-history/getting-started}{FamilySearch}}\end{flushleft}
    \begin{flushright}Salt Lake City, UT\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Statistician}\end
    {flushleft}\begin{flushright}Sep 2023 - Present\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}

* Eliminated 50+ fraudulent contractors in the African History Project by \textbf{\textit{developing and automating}} in-house tuned anomaly detection methods in \textbf{\textit{Python}} over 200k+ genealogical submissions; regularly presented abstracts to management



\vspace{7pt}

<!-- EXPERIENCE : 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://byuidatascience.github.io/lab/}{Mathematics Department BYU-Idaho}}\end{flushleft}
    \begin{flushright}Rexburg, ID\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Data Science Society President, Chief Lab Manager}\end{flushleft}
    \begin{flushright}Mar 2023 - Sep 2023\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Led and coordinated data science society activities and meetings; mentored and supported project teams including weekly bootcamps to teach \textbf{\textit{data analysis/statistics and ML hyper parameter tuning}}, over 6 teams of ~ 6-12 people each
* Managed, scheduled, and trained all tutors for all data science courses, school-wide for Data Science Lab \textbf{\textit{(R and Python)}}

\vspace{6pt}

\begin{large}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Teacher's Assistant}\end{flushleft}
    \begin{flushright}May 2022 - Present\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* **DS Programming**: Tutored data analysis, statistics, and basic ML in \textbf{\textit{Python (Pandas, NumPy, Sci-kit Learn)}}
* **Data Wrangling and viz**: Tutored complex data analysis and visualization with \textbf{\textit{R tidyverse}} (dplyr, ggplot2 etc.)
* **Big Data Programming**: Tutored big data analysis and viz. in \textbf{\textit{DataBricks (PySpark, AutoML, Polars, Plotly, etc.)}}
* **Linear Algebra**: Tutored both non-computational and computational linear algebra with \textbf{\textit{Python's NumPy and SymPy}}

\vspace{7pt}

\begin{large}
  {\bf CONSULTING}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://mbmsubmissions.blogspot.com/2019/10/}{Baltimore Mission (Spanish Outreach)}}\end{flushleft}
    \begin{flushright}Baltimore, MD\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Technology Consultant and Regional Manager}\end
    {flushleft}\begin{flushright}Mar 2019 - Feb 2020\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}

\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://github.com/wilfordwoodruff}{Wilford Woodruff Papers}}\end{flushleft}
    \begin{flushright}Rexburg, ID\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Data Scientist}\end
    {flushleft}\begin{flushright}May 2023 - Dec 2023\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Provided actionable graphs and trends using \textbf{\textit{time-series analysis}} and \textbf{\textit{NLP (sentiment analysis and textual clustering)}}
* Delivered \textbf{\textit{interactive web app in Streamlit}} that matched various corpus data together using text vectors (\textbf{\textit{NLTK}}, \textbf{\textit{sklearn}})

\vspace{7pt}
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{http://ohioelect.us/}{Ohio Voter Data Consulting}}\end{flushleft}
    \begin{flushright}Rexburg, ID\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Founder, Data Scientist}\end
    {flushleft}\begin{flushright}Sep 2023 - Present\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Democraztized \textbf{\textit{big data}} models for grassroots campaigns, \textbf{\textit{cloud computing}} ML models for ~10 million rows in \textbf{\textit{Python's sklearn}} for predictive analysis in voter behavior, visualizing data interactively with \textbf{\textit{R Shiny}}, \textbf{\textit{Plotly}}, \textbf{\textit{Quarto}}
* Awarded First Place in nationally recognized I-Hack hackathon for innovation by optimizing campaign outreach
 

\vspace{7pt}





<!-- SKILLS -->
\begin{large}{\bf SKILLS}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}
\vspace{6pt}
* **Python**: Pandas, NumPy, Sci-kit Learn, PySpark, Polars, Keras / Tensorflow, BeautifulSoup4, DataBricks
\vspace{2pt}
* **R**: CAR, Mosaic, RMarkdown, Tidyverse (dplyr, tidyr, stringr, forcats, lubridate, purrr, etc.) 
\vspace{2pt}
* **Visualization libraries**: Streamlit, ggplot2, Matplotlib / Seaborn, Plotly Express, Altair
\vspace{2pt}
* **Other Technical Skills**: Microsoft Excel, SQL, Git/GitHub, Quarto, LaTeX, Regex, Docker
\vspace{2pt}
* **Math Courses**: Calculus, Applied Calculus for Data Analysis, Linear Algebra, Intermediate Statistics, Applied Regression