---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=12mm
      - left=16mm
      - right=16mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertinus
    colorlinks: true
    fontsize: '16'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
---
<!-- TITLE -->
\begin{center}
{\fontsize{40}{60}\selectfont \textbf{Alan J Averett}}
\end{center}

<!-- CONTACT INFO -->
\begin{center} 832.856.4666 | ajaverett0@gmail.com | linkedin.com/in/ajaverett
\end{center}
\vspace{12pt}

<!-- EDUCATION: 1ST BULLET -->
\begin{large}
  {\bf EDUCATION}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf Brigham Young University- Idaho}\end{flushleft}
    \begin{flushright}Rexburg, ID\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}B.Sc. Data Science, Statistics; \textit{Major GPA: 3.9} \end{flushleft}
    \begin{flushright}Apr 2020 - Apr 2024\end{flushright}
  \end{multicols}
  \vspace{-0.25cm}
  \textit{Certifications: Web and Computer Programming; Machine Learning}
\end{large}

\vspace{0.2cm}


\vspace{7pt}

<!-- EXPERIENCE : 1ST BULLET-->
\begin{large}{\bf EXPERIENCE}
\vspace{3pt}
\hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://wpaintel.com/about/}{WPA Intelligence}}\end{flushleft}
    \begin{flushright}Washington D.C.\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Machine Learning Intern}\end{flushleft}
    \begin{flushright}Jul 2022 - Nov 2022\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Created digestible reports for 80+ political campaigns by analyzing/visualizing voter data trends with machine learning models that predicted ideological disposition and turnout using R's tidyverse
* Significantly decreased polling production time by automating sampling methodologies using R's statistical libraries
* Increased accuracy and AUC for all future machine learning models by using GIS data to categorize over 100 million records of voter data into 12 granularities of population density using R's sf and other geospatial libraries

\vspace{7pt}




<!-- EXPERIENCE : 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://byuidatascience.github.io/lab/}{Mathematics Department BYU-Idaho}}\end{flushleft}
    \begin{flushright}Rexburg, ID\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Data Science Society President}\end{flushleft}
    \begin{flushright}Mar 2023 - Sep 2023\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Oversaw and helped coordinate all projects undertaken by the society with the faculty sponsor
* Led and coordinated data science society activities and meetings; mentored and supported project teams including weekly bootcamps to teach data analysis, statistics, and machine learning

\vspace{6pt}

\begin{large}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Teacher's Assistant}\end{flushleft}
    \begin{flushright}May 2022 - Present\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* **DS Programming**: Tutored data analysis, statistics, and basic ML in Python (Pandas, NumPy, Sci-kit Learn)
* **Data Wrangling and viz**: Tutored complex data analysis and visualization with R tidyverse (dplyr, ggplot2 etc.)
* **Big Data Programming**: Tutored big data analysis and visualization in DataBricks (Polars, PySpark, Plotly, AutoML, etc.)
* **Business Statistics**: Tutored basic statistical analyses, theories, and methods with Excel
* **Linear Algebra**: Tutored both non-computational and computational linear algebra with Python (NumPy, SymPy)

\vspace{6pt}

\begin{large}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Head Lab Coordinator}\end{flushleft}
    \begin{flushright}Apr 2023 - Present\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Managed, scheduled, and trained tutors to work in the university data science lab for R and Python
* Tutored students seeking help in programming and mathematics for all intermediate level data science courses using various data science and machine learning libraries within Python including Pandas, Numpy, Sklearn, and TensorFlow



\vspace{7pt}





\begin{large}{\bf PROJECTS}
\hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://wilfordwoodruffpapers.org/}{Wilford Woodruff Papers}}\end{flushleft}
    \begin{flushright}Rexburg, ID\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Data Scientist}\end
    {flushleft}\begin{flushright}May 2023 - Present\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Provided actionable graphs and trends using NLP tools including sentiment analysis and unsupervised textual clustering alongside time-series analysis as part of the Wilford Woodruff production team
* Delivered an interactive web application that cross-referenced religious texts with 19th century published journal entries by using a Bag-of-Words model to vectorize n-grams to find textual matches sorted by confidence

\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://www.familysearch.org/help/oral-history/getting-started}{FamilySearch}}\end{flushleft}
    \begin{flushright}Rexburg, ID\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Statistician}\end
    {flushleft}\begin{flushright}Sep 2023 - Present\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}

* Identified erroneous genealogical submissions in the African Oral History Project using in-house tuned statistical models, anomaly detection methods, and machine learning algorithms to eliminate fraudulent contractors

\vspace{7pt}


<!-- SKILLS -->
\begin{large}{\bf SKILLS}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}
\vspace{6pt}
* **Python**: Pandas, NumPy, Sci-kit Learn, PySpark, Polars, Keras / Tensorflow, BeautifulSoup4, DataBricks
\vspace{2pt}
* **R**: CAR, Mosaic, RMarkdown, Tidyverse (dplyr, tidyr, stringr, forcats, lubridate, purrr, etc.) 
\vspace{2pt}
* **Visualization libraries**: Streamlit, ggplot2, Matplotlib / Seaborn, Plotly Express, Altair
\vspace{2pt}
* **Other Technical Skills**: Microsoft Excel, SQL, Git/GitHub, Quarto, LaTeX, Regex, Docker
\vspace{2pt}
* **Math Courses**: Calculus, Applied Calculus for Data Analysis, Linear Algebra, Discrete Mathematics, Applied Regression

